<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Alaa-Saber" failures="1" tests="7" name="seleniumTask.LogInPage" time="24.521" errors="0" timestamp="2022-04-08T07:50:59 EET" skipped="0">
  <testcase classname="seleniumTask.LogInPage" name="createNewAccountWith_Registered_Email" time="2.167"/>
  <system-out/>
  <testcase classname="seleniumTask.LogInPage" name="logInWith_Valid_Email_Valid_Password" time="6.699"/>
  <system-out/>
  <testcase classname="seleniumTask.LogInPage" name="createNewAccountWith_UnRegistered_Email" time="1.407">
    <failure message="expected [create an account] but found [authentication]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [create an account] but found [authentication]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at seleniumTask.LogInPage.createNewAccountWith_UnRegistered_Email(LogInPage.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createNewAccountWith_UnRegistered_Email -->
  <system-out/>
  <testcase classname="seleniumTask.LogInPage" name="logInWith_NO_Email_NO_Password" time="4.235"/>
  <system-out/>
  <testcase classname="seleniumTask.LogInPage" name="logInWith_In_Valid_Email_Valid_Password" time="2.224"/>
  <system-out/>
  <testcase classname="seleniumTask.LogInPage" name="logInWith_Valid_Email_InValid_Password" time="3.475"/>
  <system-out/>
  <testcase classname="seleniumTask.LogInPage" name="createNewAccountWith_InValid_Email_Format" time="4.314"/>
  <system-out/>
</testsuite> <!-- seleniumTask.LogInPage -->
